apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-yvwi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-yvwi
    app.kubernetes.io/part-of: test-app-ltje
  name: test-component-yvwi
  namespace: build-e2e-hacbs-sabe
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-yvwi
status:
  loadBalancer: {}
